---
title: "Introduction"
---


This dashboard is part of the [epiENGAGE](https://epiengage.org) project, a CDC-funded collaboration involving over 20 research labs and public health departments dedicated to developing science-based tools and training programs that help local agencies detect, forecast, and respond to outbreaks more effectively. 

This particular dashboard is designed for the [Flu Metrocast hub](https://github.com/reichlab/flu-metrocast/tree/main), a national platform enabling collaborative, local-level forecasting of influenza-related emergency department visits and hospital admissions.

::: {style='display:flex; align-items: center; justify-content: center'}

[View The Latest Forecasts](forecast.html){.btn .btn-primary role="button"}

:::


## Current Metro Areas
::: columns
::: column
- New York City
  - Target: Percent of ED visit due to ILI (Influenza-like Illness) 
  - Data source : [New York City Department of Health and Mental Hygiene](https://a816-health.nyc.gov/hdi/epiquery/visualizations?PageType=ps&PopulationSource=Syndromic)
  - Target areas: NYC (citywide)

:::

::: column
- Local Flu Activity Across U.S. Metro Areas
  - Target: Percentage of ED visits due to flu
  - Data Source : CDC's [Emergency Department Visits for Viral Respiratory Illness](https://data.cdc.gov/Public-Health-Surveillance/NSSP-Emergency-Department-Visit-Trajectories-by-St/rdmq-nq56/about_data)
  - Target areas:  51 metropolitan Health Service Areas (HSAs) across Colorado, Georgia, Indiana, Maine, Maryland, Massachusetts, Minnesota, South Carolina, Texas, Utah, and Virginia.  
  A full list of included HSAs is available [here](https://github.com/reichlab/flu-metrocast/blob/main/auxiliary-data/locations.csv).
  - Note: These HSAs include a central city and its surrounding counties, and we include all HSAs with populations of at least 250,000 (with the exception of Massachusetts).
    
:::

::: column
- North Carolina
  - Target: Percentage of ED visits due to flu
  - Data Source: [North Carolina Division of Public Health's (NC DPH) statewide syndromic surveillance system](https://www.dph.ncdhhs.gov/)
  - Target areas: 7 geographic regions comprised of adjacent counties
:::

:::
    
##  Models Included

- epiENGAGE-GBQR : A machine learning method that combines gradient boosting and quantile regression to predict conditional quantiles
- epiENGAGE-INFLAenza : A spatial time-series model that uses the R-INLA package for estimating forecast posterior distributions.
- epiENGAGE-Copycat :  A pattern matching model that matches growth rate trends to historic growth rate curves.
- Epiforecasts-dyngam : A Bayesian hierarchical GAM with a univariate AR(1) process
- epiENGAGE-baseline : simple time series model as a reference model
- epiENGAGE-ensemble_mean : An equally weighted mean ensemble that takes the mean at each quantile level of all eligible forecasts
- epiENGAGE-log_norm : Linear pool (a.k.a. distributional mixture) ensemble of quantile forecast submissions.


