---
title: "Untitled"
format: html
---

---
title: "Data"
format: 
  html: 
    code-overflow: wrap
    embed-resources: true
    self-contained-math: true
---

## What is National Syndromic Surveillance Program (NSSP) data?

National Syndromic Surveillance Program (NSSP) data are collected by the U.S. Centers for Disease Control and Prevention, in collaboration with local and state health departments and private sector partners. NSSP data include surveillance data tracking the percentage of emergency department (ED) visits due to influenza-like illness, including influenza, COVID-19, and RSV. NSSP data reporting of ED visits due to influenza-like illness began in late 2022. Data are available on a weekly time scale, with data from the prior week added Friday mornings. 

## What sub-state-level data are available?

At the sub-state level, reporting facilities can be aggregated to the level of health service area (HSA). HSAs are single- or multi-county clusters that correspond with healthcare-seeking patterns. All publicly-available county-level NSSP data are really HSA values, such that each county in the HSA will have the same value as the parent HSA. 

A list of HSAs can be downloaded [here](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fseer.cancer.gov%2Fseerstat%2Fvariables%2Fcountyattribs%2FHealth.Service.Areas.xls&wdOrigin=BROWSELINK).

## Missingness

There is substantial missingness at the county level, especially for rural and lower-population locations.

Missingness has varied a bit since reporting began in late 2022. As of January 2025, NSSP does not report any data at the county level for the following states: Alaska, Alabama, Arkansas, Arizona, California, Florida, Missouri, North Dakota, New Hampshire, Ohio, Pennsylvania, Rhode Island, South Dakota, and Washington. 

Of these, no county-level data is available since reporting began for Alaska, Alabama, Arkansas, Arizona, California, Florida, Missouri, North Dakota, New Hampshire, Ohio, South Dakota, and Washington. 

**We are open to working with public health partners from jurisdictions with no reported NSSP county-level data if they are able to facilitate access to an alternative source of sub-state-level data.**

## Accessing NSSP data

NSSP data can be accessed through the [epidata API](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/nssp.html) using `epidatr` (recommended) and `covidcast` R packages.

A vignette for using `epidatr` is available on [CRAN](https://cran.r-project.org/web/packages/epidatr/vignettes/epidatr.html).
